const constants = {
    LIKE: "LIKE",
    LIST_DETAILS: "LIST_DETAILS",
    ADD_ART: "ADD_ART",
    REMOVE_ART: "REMOVE_ART",
    ADD_TO_COLLECTION: "ADD_TO_COLLECTION",
    FLIP_CARD: "FLIP_CARD",
    ADD_ERROR: "ADD_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    FETCH_TITLES: "FETCH_TITLES",
    CANCEL_FETCHING: "CANCEL_FETCHING",
    CHANGE_SUGGESTIONS: "CHANGE_SUGGESTIONS",
    CLEAR_SUGGESTIONS: "CLEAR_SUGGESTIONS"
};

export default constants;